### ISSUE TITLE
Note di piè di pagina sbagliate su PDF

### ISSUE THREAD

**Issue by rmontagnin** [gigiobello/sweki#1]
Ti segnalo alcune note di piè di pagina sbagliate che ho trovato nella versione PDF:
1. Pagina 8, entrambe le note 4 e 5 riportano "Per ritiro s’intende il momento in cui il prodotto cessa di essere seguito dai creatori"
2. Pagina 10, entrambe le note 6 e 7 riportano "Project manager."
3. Pagina 11, la note 8 riporta "Project manager."
4. Pagina 12, le note 9, 10, 11, 12 riportano "Project manager"
5. Pagina 13, le note 13 e 14 riportano entrambe "Project administrator, da non confondere con il project manager: il primo è sottoposto al secondo." 
6. Pagina 14, le note 15 e 16 riportano entrambe "Project administrator, da non confondere con il project manager: il primo è sottoposto al secondo."

**Comment by ggiuffre** [comment]
Purtroppo il template XSLT ha un bug proprio per tradurre le note a piè pagina:

    <xsl:template match="sup[@class='footnote']">
        <xsl:variable name="ftn" select="'substring(a/@href, 5)'" />
        \footnote{<xsl:value-of select="/html/body/div[@id='footnotes']/ol/li[$ftn]" />}
    </xsl:template>

Intanto, però, la [versione originale](https://fiup.github.io/sweki/) (in HTML) non ha questo problema.

**Comment by ggiuffre** [comment]
(il bug è dovuto al fatto che XSLT non permette di aggiornare variabili; nello specifico, la variabile `$ftn` rimane sempre uguale a 1.)
